name: 'Code Owners Validator'
description: 'Validates globs of CODEOWNERS file and validates coverage of source folders'
author: 'Rufat Khaslarov / Dzmitry Patsiakevich'
inputs:
  path:
    required: true
    description: 'File Path to Code Owners file'
    default: ./.github/CODEOWNERS
  folders:
    required: true
    description: 'Folders that should be tracked'
    default: ./.github/CODEOWNERS
runs:
  using: 'node18'
  main: 'dist/index.js'
